---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-aa2-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-aa2-kubernetes
  template:
    metadata:
      labels:
        app: my-aa2-kubernetes
    spec:
      containers:
      - name: my-aa2-kubernetes
        image: asalasher/nodeforAA2:v1
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "64Mi"
            cpu: "80m"
          limits:
            memory: "128Mi"
            cpu: "250m"